### ISSUE TITLE
Regression: ERA5 is not working because "time" variable has changed name to "valid_time"

### ISSUE THREAD

**Issue by davidosterberg** [MET-OM/metocean-api#46]
This is a regression. It was previosly fixed in PR #21

![image](https://github.com/user-attachments/assets/0d40ac74-e919-49fc-bf5f-14d0c8755ee2)

Error occurs because the create_dataframe function incorrectly assumes that the variable is called "time"

![image](https://github.com/user-attachments/assets/63492c23-2ce2-464d-9770-57b82c4ccf89)

**Comment by lassebje** [comment]
@davidosterberg I am sorry about the regression here. There should be standard tests for this functionality but the issue is you will then need to keep personal keys within the build setup, which is not a good thing. 

There are several potential fixes here. 
See https://github.com/MET-OM/metocean-api/blob/e03f84dec278b707d1067ed28823c82af9b72d88/metocean_api/ts/internal/metno/met_products.py#L366 for how this was solved for he NORA3StormSurge product. Here the time dimension is renamed when storing to the cache.
It is my suggestion we do the same for the ERA5 dataset
